name: fluetooth
description: Flutter library for sending bytes to Bluetooth devices.
version: 0.0.6
repository: https://www.github.com/iandis/fluetooth
issue_tracker: https://www.github.com/iandis/fluetooth/issues

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: app.iandis.fluetooth
        pluginClass: FluetoothPlugin
      ios:
        pluginClass: FluetoothPlugin
